// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXqKoY6RdhFOfBSLrrDUx76o0KcHthPU',
    appId: '1:334713910038:web:9d792d2fb53b442b385637',
    messagingSenderId: '334713910038',
    projectId: 'techjet-32be2',
    authDomain: 'techjet-32be2.firebaseapp.com',
    storageBucket: 'techjet-32be2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAH6wrsIE3D6-45QRHw0GV5X-o1V6JQ_I',
    appId: '1:334713910038:android:f097f80174b62936385637',
    messagingSenderId: '334713910038',
    projectId: 'techjet-32be2',
    storageBucket: 'techjet-32be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlUn3g0hlooS3aR3EUPeTUq82BN9hBq0',
    appId: '1:334713910038:ios:5cdf5d0d638eadfd385637',
    messagingSenderId: '334713910038',
    projectId: 'techjet-32be2',
    storageBucket: 'techjet-32be2.appspot.com',
    iosBundleId: 'com.example.minnal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlUn3g0hlooS3aR3EUPeTUq82BN9hBq0',
    appId: '1:334713910038:ios:f792a11e10251ff3385637',
    messagingSenderId: '334713910038',
    projectId: 'techjet-32be2',
    storageBucket: 'techjet-32be2.appspot.com',
    iosBundleId: 'com.example.minnal.RunnerTests',
  );
}
